### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by UnknownNull** [cooldogedev/TNTTag#12] opened 2023-02-01 15:35 UTC
![image](https://user-images.githubusercontent.com/91208232/216088269-1239a867-de6b-485e-b345-ae20a6344f03.png)

**Comment by cooldogedev** [comment] 2023-02-01 17:33
Closing due to lack of information, create a new one when you gather more information e.g. how to reproduce the issue and what version you're on. Anyways this error should never occur otherwise would've been reported before.

**Closed as completed by cooldogedev** 2023-02-01 17:33 UTC

**Comment by UnknownNull** [comment] 2023-02-01 17:44
TntTag: lasted version
Pmmp: api4

**Comment by cooldogedev** [comment] 2023-02-01 17:46
> how to reproduce

**Comment by UnknownNull** [comment] 2023-02-01 17:49
Phar
